config/routes.rb
TestBoutwikFinal::Application.routes.draw do
  root :to => 'home#index'

  resources :products
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :product

  mount_uploader :picture, PictureUploader

  validates_presence_of :description, :title
  attr_accessible :description, :picture, :title
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :articles

  mount_uploader :picture, PictureUploader

  validates_presence_of :description, :name
  attr_accessible :description, :name, :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Product.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/articles/_form.html.haml
= simple_form_for @article, :html => {:multipart => true} do |f|
  - if @article.errors.any?
    #error_explanation
      %h2
        = "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.input :title, label: 'Title', :placeholder => 'title'
  .form-group
    = f.input :description, label: 'Description', :placeholder => 'Describe your Product'
  .form-group
    = f.input :picture, label: 'Picture', :type => 'file'
  %button.btn.btn-default{:type => "submit"}
    Submit

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h1
  Listing articles
.link
  = link_to 'New Article', new_article_path

- @articles.each do |article|
  .col-md-4
    .article
      %h2
        = article.title
      %p.description
        = article.description
      .more
        = link_to 'Show', article
        = link_to 'Edit', edit_article_path(article)
        = link_to 'Destroy', article, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @article.title
%p
  %b Description:
  = @article.description
%p
  %b
    Picture:
  = image_tag(@article.picture_url, :width => 200) if @article.picture.present?

= link_to 'Edit', edit_article_path(@article)
\|
= link_to 'Back', articles_path

app/views/home/index.html.haml
.jumbotron
  %h1 Welcome
  %p
    This is a test for Boutwik!!! Warning, Lorem ipsum are coming.
    %br
    My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there.
  #button-wrapper
    .button
      = link_to 'Products', products_path, :class => 'product btn btn-lg btn-success', :role => 'button'
    .button
      = link_to 'Articles', articles_path, :class => 'btn btn-lg btn-success', :role => 'button'

app/views/layouts/application.html.haml
%head
  %title
    Test Boutwik Final
  = stylesheet_link_tag "application", :media => "all"
  = csrf_meta_tag

%body
  .navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
    .container
      .navbar-header
        = link_to 'Test for Boutwik', '/', :class => 'navbar-brand'
      .navbar-collapse.collapse
        %ul.nav.navbar-nav
          %li
            = link_to 'Products', products_path
          %li
            = link_to 'Articles', articles_path
  #container
    = yield

  = javascript_include_tag "application"

app/views/products/_form.html.haml
= simple_form_for @product, :html => {:multipart => true} do |f|
  - if @product.errors.any?
    #error_explanation
      %h2
        = "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.input :name, label: 'Name', :placeholder => 'name'
  .form-group
    = f.input :description, label: 'Description', :placeholder => 'Describe your Product'
  .form-group
    = f.input :picture, label: 'Picture', :type => 'file'
  %button.btn.btn-default{:type => "submit"}
    Submit

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
%h1
  Listing products
.link
  = link_to 'New Product', new_product_path

- @products.each do |product|
  .col-md-4
    .product
      %h2
        = product.name
      %p.description
        = product.description
      .more
        = link_to 'Show', product
        = link_to 'Edit', edit_product_path(product)
        = link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @product.name
%p
  %b Description:
  = @product.description
%p
  %b
    Picture:
  = image_tag(@product.picture_url, :width => 200) if @product.picture.present?

= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path